import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const GOOGLE_CLOUD_VISION_API_KEY = Deno.env.get("GOOGLE_CLOUD_VISION_API_KEY");
    if (!GOOGLE_CLOUD_VISION_API_KEY) {
      throw new Error("GOOGLE_CLOUD_VISION_API_KEY is not configured");
    }

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) {
      throw new Error("LOVABLE_API_KEY is not configured");
    }

    const { image } = await req.json();
    if (!image) {
      return new Response(JSON.stringify({ error: "No image provided" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Run Vision API (SafeSearch) and Gemini AI detection in parallel
    const [visionResult, aiResult] = await Promise.all([
      // 1. Google Cloud Vision for SafeSearch
      fetch(`https://vision.googleapis.com/v1/images:annotate?key=${GOOGLE_CLOUD_VISION_API_KEY}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          requests: [{
            image: { content: image },
            features: [
              { type: "SAFE_SEARCH_DETECTION" },
              { type: "LABEL_DETECTION", maxResults: 10 },
            ],
          }],
        }),
      }).then(async (r) => {
        if (!r.ok) throw new Error(`Vision API error: ${await r.text()}`);
        return r.json();
      }),

      // 2. Gemini Pro for AI-generated detection (stronger model for accuracy)
      fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${LOVABLE_API_KEY}`,
        },
        body: JSON.stringify({
          model: "google/gemini-2.5-pro",
          messages: [
            {
              role: "system",
              content: `You are an expert forensic image analyst specializing in detecting AI-generated images. You have extensive experience identifying outputs from DALL-E 3, ChatGPT image generation, Midjourney, Stable Diffusion, Flux, and other generative AI tools. You err on the side of flagging images as AI-generated when uncertain. Modern AI generators produce extremely realistic images, so you must be vigilant.`
            },
            {
              role: "user",
              content: [
                {
                  type: "text",
                  text: `Carefully analyze this image to determine if it was generated by AI or is a genuine photograph.

CRITICAL: Modern AI image generators (especially ChatGPT/DALL-E 3, Midjourney v6+) produce EXTREMELY realistic images. Do NOT assume an image is real just because it looks realistic. Look deeper.

AI-GENERATED indicators (even ONE strong indicator means AI-generated):
1. PERFECTION: Unnaturally perfect fur, skin, hair textures - too clean, too uniform
2. BOKEH: Overly smooth, perfectly circular bokeh - real cameras produce imperfect bokeh
3. LIGHTING: Too-perfect golden hour lighting, studio-quality lighting in casual scenes
4. COMPOSITION: Perfectly centered subject, ideal framing that looks "stock photo perfect"
5. EYES: Unnaturally clear/bright/perfect eyes, especially in animals
6. DEPTH OF FIELD: Artificially smooth background blur transitions
7. TEXTURES: Ground/surface textures that look painted or generated rather than photographed
8. ANATOMY: Subtle anatomical issues - extra toes, merged features, impossible poses
9. COLORS: Hyper-saturated or impossibly warm color grading
10. OVERALL FEEL: Image looks "too perfect" or "too cute" - like a professional render
11. NOISE: Lack of natural camera sensor noise/grain
12. DETAILS: Background elements that dissolve into abstract shapes upon close inspection

IMPORTANT: If the image looks like it could be from a professional stock photo or AI art portfolio, lean toward AI-generated. Real casual photos have imperfections.

Respond with ONLY a JSON object (no markdown, no code fences):
{"isAiGenerated": true/false, "confidence": 0-100, "reasoning": "brief explanation of specific indicators found"}`
                },
                {
                  type: "image_url",
                  image_url: { url: `data:image/jpeg;base64,${image}` }
                }
              ]
            }
          ],
          temperature: 0.1,
          max_tokens: 500,
        }),
      }).then(async (r) => {
        if (!r.ok) throw new Error(`AI Gateway error: ${await r.text()}`);
        return r.json();
      }),
    ]);

    // Parse Vision API results
    const annotation = visionResult.responses?.[0];
    if (!annotation) throw new Error("No response from Vision API");

    const safeSearch = annotation.safeSearchAnnotation || {};
    const adult = safeSearch.adult || "UNKNOWN";
    const violence = safeSearch.violence || "UNKNOWN";
    const racy = safeSearch.racy || "UNKNOWN";
    const medical = safeSearch.medical || "UNKNOWN";

    const highRisk = ["LIKELY", "VERY_LIKELY"];
    const isSensitive =
      highRisk.includes(adult) ||
      highRisk.includes(violence) ||
      highRisk.includes(racy);

    const labels: string[] = (annotation.labelAnnotations || []).map(
      (l: { description: string }) => l.description
    );

    // Parse Gemini AI detection result
    let isAiGenerated = false;
    let aiConfidence = 50;
    try {
      const aiContent = aiResult.choices?.[0]?.message?.content || "";
      const cleaned = aiContent.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
      const parsed = JSON.parse(cleaned);
      isAiGenerated = parsed.isAiGenerated === true;
      aiConfidence = Math.max(0, Math.min(100, parsed.confidence || 50));
    } catch (e) {
      console.error("Failed to parse AI detection response:", e);
    }

    const result = {
      isAiGenerated,
      aiConfidence,
      isSensitive,
      sensitiveCategories: { adult, violence, racy, medical },
      labels: labels.slice(0, 10),
    };

    return new Response(JSON.stringify(result), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error: unknown) {
    console.error("Analysis error:", error);
    const message = error instanceof Error ? error.message : "Unknown error";
    return new Response(JSON.stringify({ error: message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});